# Generated by Django 5.2.7 on 2025-10-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrueba', '0002_rename_nombre_rol_nombre_rol_remove_rol_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
